# Generated by Django 5.0.3 on 2024-06-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.categorymodel'),
        ),
    ]
